import { Fragment } from "react";
import Head from "next/head";

import Layout from "../../shared/Layout";
import RestaurantDetail from "../../features/restaurantDetail";
import { restaurantGetAPI } from "../../api/restaurant";

const Restaurants = (props) => {
  return (
    <Fragment>
      <Head>
        <title>Restaurants | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <RestaurantDetail data={props} />
      </Layout>
    </Fragment>
  );
};

export default Restaurants;

export const getServerSideProps = async (context) => {
  const slug = context.query.name;
  const restaurant = await restaurantGetAPI(slug);

  return {
    props: {
      restaurant: restaurant.data.restaurant,
    },
  };
};
