import { Fragment } from "react";
import Head from "next/head";

import Layout from "../../shared/Layout";
import FaqsContainer from "../../features/faqs";

const Faqs = () => {
  return (
    <Fragment>
      <Head>
        <title>FAQ'S | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <FaqsContainer />
      </Layout>
    </Fragment>
  );
};

export default Faqs;
