import { Fragment } from "react";
import Head from "next/head";

import Layout from "../../shared/Layout";
import AboutContainer from "../../features/about";

const About = () => {
  return (
    <Fragment>
      <Head>
        <title>About us | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <AboutContainer />
      </Layout>
    </Fragment>
  );
};

export default About;
