import { Fragment } from "react";
import Head from "next/head";

import Layout from "../../shared/Layout";
import ErrorContainer from "../../features/404";

const ErrorPage = () => {
  return (
    <Fragment>
      <Head>
        <title> Page is not found | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <ErrorContainer />
      </Layout>
    </Fragment>
  );
};

export default ErrorPage;
