import { Fragment } from "react";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "../store";
import GlobalStyle from "../styles/global";

function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;900&family=Mukta:wght@400;500;600&family=Open+Sans:wght@400;600&family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        ></link>
        <title>Foody Delivery</title>
      </Head>
      <Provider store={store}>
        <GlobalStyle />
        <Component {...pageProps} />
      </Provider>
    </Fragment>
  );
}

export default MyApp;
