import { Fragment } from "react";
import Head from "next/head";

import Layout from "../shared/Layout";
import HomeContainer from "../features/home";

const Home = () => {
  return (
    <Fragment>
      <Head>
        <title>Home | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <HomeContainer />
      </Layout>
    </Fragment>
  );
};

export default Home;
