import { Fragment } from "react";
import Head from "next/head";

import Layout from "../../shared/Layout";
import HowItWorkContainer from "../../features/how-it-works";

const HowItWork = () => {
  return (
    <Fragment>
      <Head>
        <title>How it works | Foody Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/food-delivery-logo.jpg" />
      </Head>
      <Layout>
        <HowItWorkContainer />
      </Layout>
    </Fragment>
  );
};

export default HowItWork;
